MugedaHelper={};function G(a){return document.getElementById(a)}function E(a,b,c){b||(b="load");c||(c=window);c.attachEvent?c.attachEvent("on"+b,a):c.addEventListener(b,a,false)}function json(a){try{return eval("("+a+")")}catch(b){return null}}function _39(a){if(!a||typeof a=="string")return a;var b="",c;for(c in a)b+="&"+c+"="+encodeURIComponent(a[c]);b&&(b=b.substr(1));return b}
function ajax(a){var b=/POST/i.test(a.type),c=a.data||"",e=a.dataType,f=a.url||location.href,d=/\?/.test(f)?"&":"?",g=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP")||new ActiveXObject("Microsoft.XMLHTTP");g.onreadystatechange=function(c){if(g.readyState==4)g.status==200?(c=g.responseText,e=="json"&&(c=json(c)),(b=a.success)&&b(c)):a.error&&a.error(g.status,g)};if(typeof c=="object"){var j=[],i;for(i in c)j.push(encodeURIComponent(i)+"="+encodeURIComponent(c[i]));c=j.join("&")}g.open(b?
"POST":"GET",f+(b?"":(c?d:"")+c+(a.cache?"":(!c&&d=="?"?"?":"&")+(a.cache_ok?"":"_="+(new Date).getTime()))),a.async===false?false:true);b&&g.setRequestHeader("Content-Type","application/x-www-form-urlencoded");g.send(c);return g}
var ajaxHelper=function(a){a=a||{};a.method=a.method||"GET";a.type=(a.type||"text").toLowerCase();a.success=a.success||function(){};a.error=a.error||function(){};a.cache_ok=a.cache_ok||false;a.url=a.url||(a.error({status:-5,desc:"Empty url"}),"");a.mode=a.mode||null;var b=(new Date).getTime()+""+Math.random(),b=b.replace(".","");a.jsonp_callback=a.jsonp_callback||"callback_"+b;window.hashOptions=window.hashOptions||{};window.hashOptions[b]=a;window.hashOptions[""]=a;a.cache_ok||(a.url+=a.url.indexOf("?")>
-1?"&":"?",a.url+="_mats="+b,a.url+="&callback="+a.jsonp_callback);if(a.type=="jsonp")if(a.mode&&a.mode=="postMessage"){var c=(location.protocol||"http:")+"//weika.mugeda.com";if(!window._POSTMESSAGE)window.addEventListener("message",function(a){if(a.data){if(a.data.callbackName&&window[a.data.callbackName])window[a.data.callbackName](a.data.res,a.data.mats)}else console.log("postMessage请求失败")}),window._POSTMESSAGE=true;var e="postMessage_"+b;window[e]=function(c){a.success(c);
d.removeChild(document.getElementById(b));delete window[e]};var f={url:a.url,form:a.form||{},mats:b,callbackName:e,dataType:a.postMessageType||"JSONP",isPost:a.isPost||false},d=document.getElementsByTagName("head")[0],g=document.createElement("iframe");g.id=b;g.src="//weika.mugeda.com/server/postMessage.html";d.appendChild(g);g.onload=function(){g.contentWindow.postMessage(f,c)};g.onerror=function(){alert("postMessage模块加载失败。")}}else if(a.mode&&a.mode=="iframe"){d=
document.getElementsByTagName("head")[0];e=a.jsonp_callback+"_"+b;window[e]=function(c){a.success(c);d.removeChild(document.getElementById(b));delete window[e]};g=document.createElement("iframe");d.appendChild(g);var j=g.contentDocument;g.id=b;j.open();j.write('<html><head><title>_iframe</title></head><body><script>window["'+a.jsonp_callback+'"] = function (data) {window.parent["'+e+'"](data)}<\/script><script type="text/javascript" src="'+a.url+'"><\/script></body></html>');j.close()}else window[a.jsonp_callback]=
function(a){var b=window.hashOptions[a._mats||""];b.success(a);delete window[b.jsonp_callback]},d=document.getElementsByTagName("head")[0],j=document.createElement("script"),j.type="text/javascript",j.src=a.url,j._mats=b,j.onload=function(){},j.onerror=function(){window.hashOptions[this._mats||""].error({status:-2,desc:"Failed to load the url: "+a.url})},d.appendChild(j);else if(a.type=="fetch"&&window.fetch)try{fetch(a.url,{method:a.method||"GET",credentials:a.credentials||"include"}).then(function(b){b.status!==
200?a.error&&a.error({status:b.status,desc:"Error in fetching data "+b.statusText}):b.json().then(function(b){a.success(b)})})}catch(i){a.error&&a.error({status:-1,desc:"Error in fetching data "+i.toString()})}else{var h;window.XMLHttpRequest?h=new XMLHttpRequest:a.error({status:-3,desc:"Platform not supported"});h.withCredentials=a.withCredentials||true;h.onreadystatechange=function(){if(h.readyState==4)if(h.status==200){var b="ok";if(a.type=="json")try{a.success(JSON.parse(h.responseText))}catch(c){b=
c.toString(),a.error({status:-6,desc:"Error in parsing JSON ("+b+")"})}else a.type=="data"||a.type=="buffer"?a.success(h.response):a.type=="text"&&a.success(h.responseText)}else a.error({status:h.status,desc:"Error in fetching data (code "+h.status+")"})};if(a.type=="data")h.responseType="blob";else if(a.type=="buffer")h.responseType="arraybuffer";h.open(a.method,a.url,true);h.send()}};
function isMobile(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?true:false}function fo(a){var b=0,c=0;do b+=a.offsetLeft||0,c+=a.offsetTop||0;while(a=a.offsetParent);return{x:b,y:c}}function fe(a){a=a||event;return{x:a.pageX||a.x,y:a.pageY||a.y}}
function fc(a){a&&a.stopPropagation?a.stopPropagation():event.cancelBubble=true}function getClass(a,b){for(var c=RegExp("(^|\\s*)"+a+"(\\s*|$)"),e=b?document.getElementsByTagName(b):document.getElementsByTagName("*")||document.all,f=[],d=0,g=e.length;d<g;d++)c.test(e[d].className)&&f.push(e[d]);return f}
var setCookie=function(a,b,c){var e=new Date,f=window.location.host.split("."),d=f.length,g="",g=d>=2?"."+f[d-2]+"."+f[d-1]:".mugeda.com";e.setDate(e.getDate()+c);document.cookie=a+"="+escape(b)+(c==null?"":";expires="+e.toGMTString())+"; domain="+g+"; path=/"},getCookie=function(a){if(document.cookie.length>0){var b=document.cookie.indexOf(a+"=");if(b!=-1){b=b+a.length+1;c_end=document.cookie.indexOf(";",b);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(b,c_end))}}return""},
getMsuid=function(a){if(!a||typeof a!="function")return window.__MSUID||0;if(window.__MSUID)return a&&a(window.__MSUID),window.__MSUID;window._msuidQueue||(window._msuidQueue={});var b=window._msuidQueue,c=((new Date).getTime()+""+Math.random()).replace(".","");b[c]=a;var e=function(){window._msuidFrameLoaded=true;window._msuidFrame.contentWindow.postMessage({getMsuid:true,msuidCallbackName:c},(location.protocol||"http:")+"//card.mgd5.com")},a=function(a){var c=document.getElementsByTagName("head")[0],
g=document.createElement("iframe");g.src="//card.mgd5.com/card/getMsuid.html";g.id="postMessage-msuid";g.addEventListener("load",e);window.addEventListener("message",function(a){if(a.data&&a.data.type==="getMsuid"){window.__MSUID=a.data.msuid;if(b[a.data.msuidCallbackName])b[a.data.msuidCallbackName](a.data.msuid);delete b[a.data.msuidCallbackName]}else console.log("postMessage收到未识别消息类型："+(a.data?a.data.type:"（未定义）")+", 忽略...")});
g.onerror=function(){console.log("getMsuid模块加载失败")};c.appendChild(g);window._msuidFrame=g;a&&a()};window._msuidFrame?window._msuidFrameLoaded?e():window._msuidFrame.addEventListener("load",e):a()};if(window.Mugeda)Mugeda.getMsuid=getMsuid;JSON.clone=function(a){return JSON.parse(JSON.stringify(a))};function getElementOffset(a){for(var b=0,c=0;a&&a.tagName!="BODY";)b+=a.offsetTop,c+=a.offsetLeft,a=a.offsetParent;return{top:b,left:c}}Mugeda=window.Mugeda||{};
window._mrmcp=window._mrmcp||{};var creative_path=_mrmcp.creative_path||"";creative_path.length&&creative_path[creative_path.length-1]!="/"&&(creative_path+="/");var MugedaTools=window.MugedaTools=window.MugedaTools||{};
MugedaTools.message=function(){var a,b=[],c={},e=function(){var a=window.getComputedStyle(document.documentElement,""),a=(Array.prototype.slice.call(a).join("").match(/-(moz|webkit|ms)-/)||["",""])[1];return{dom:"WebKit|Moz|MS".match(RegExp("("+a+")","i"))[1],lowercase:a,css:"-"+a+"-",js:a[0].toUpperCase()+a.substr(1)}}();return{show:function(f,d){d=d||{};if(!a){var g=document.createElement("div");g.className="mugeda_mask";var j=d.parent||document.body,i=d.hideShade,h=d.center,t=d.clickable,p=g.appendChild(document.createElement("div")),
k=p.appendChild(document.createElement("div")),m=p.appendChild(document.createElement("div"));g.style.cssText=t?"text-align: center; display: block; position: absolute;left: 50%; top: 50%; transform: translate(-50%, -50%);":"position:fixed;left:0;right:0;top:0;bottom:0;text-align:center;line-height:"+(d.parent?j.offsetHeight:document.body.clientHeight||document.documentElement.clientHeight)+"px";p.style.cssText="padding-top:10px; line-height:30px;display:inline-block;padding:8px; background-color:rgba(0,0,0,"+
(i?0:0.6)+");border-radius:4px;"+(h?"position:relative;top:32px;":"");p.align="center";k.style.cssText="width: 24px; height: 24px; display: block; border-radius: 50%; border-left: 2px solid #F36523; border-top: 2px solid #F36523; border-right: 2px solid white; border-bottom: 2px solid white; margin: 16px;";m.style.cssText='text-align:center;color:#fff;font:normal 12px "microsoft yahei";';m.innerHTML=f||"";a=j.appendChild(g);i="from {"+e.css+"transform:rotate( 0deg ) }to {"+e.css+"transform:rotate( 360deg ) }";
g=document.createElement("style");document.head.appendChild(g);g=g.sheet;j="spin_"+(new Date).getTime();i="@"+e.css+"keyframes "+j+"{ "+i+"}";if(b.length)h=b.pop().name,t=c[h],delete c[h],g.deleteRule(t),g.insertRule(i,t),c[j]=t;else{h=g.cssRules.length;try{g.insertRule(i,h)}catch(r){}c[j]=h}k.style.cssText+=e.css+"animation:"+j+" 1200ms linear infinite;"}},close:function(){a&&(a.parentNode.removeChild(a),a=null)}}}();
MugedaTools.iterate=function(a,b,c){for(var e in a)a.hasOwnProperty(e)&&(typeof a[e]=="object"?iterate(a[e],b+"."+e,c):c&&c(a,e))};
MugedaTools.detectSecurityRisk=function(a){a=(a||"").toLowerCase();return a.match(/\b(fscommand|onabort|onactivate|onafterprint|onafterupdate|onbeforeactivate|onbeforecopy|onbeforecut|onbeforedeactivate|onbeforeeditfocus|onbeforepaste|onbeforeprint|onbeforeunload|onbeforeupdate|onblur|onbounce|oncellchange|onchange|onclick|oncontextmenu|oncontrolselect|oncopy|oncut|ondataavailable|ondatasetchanged|ondatasetcomplete|ondblclick|ondeactivate|ondrag|ondragend|ondragleave|ondragenter|ondragover|ondragdrop|ondragstart|ondrop|onend|onerror|onerrorupdate|onfilterchange|onfinish|onfocus|onfocusin|onfocusout|onhashchange|onhelp|oninput|onkeydown|onkeypress|onkeyup|onlayoutcomplete|onload|onlosecapture|onmediacomplete|onmediaerror|onmessage|onmousedown|onmouseenter|onmouseleave|onmousemove|onmouseout|onmouseover|onmouseup|onmousewheel|onmove|onmoveend|onmovestart|onoffline|ononline|onoutofsync|onpaste|onpause|onpopstate|onprogress|onpropertychange|onreadystatechange|onredo|onrepeat|onreset|onresize|onresizeend|onresizestart|onresume|onreverse|onrowsenter|onrowexit|onrowdelete|onrowinserted|onscroll|onseek|onselect|onselectionchange|onselectstart|onstart|onstop|onstorage|onsyncrestored|onsubmit|ontimeerror|ontrackchange|onundo|onunload|onurlflip|seeksegmenttime|javascript|eval|fromcharcode|window(\.|\['|\[")|document(\.|\['|\["))\b/g)||a.match(/\b(background\-image\s*\:|background\s*\:|href\s*\=|src\s*\=|style\s*\=)/g)||
a.match(/\<(script|link|img|input|style|meta|iframe|frame|table|td|tr|div|base|object|embed|xml)/g)};
MugedaMraid={mraidReadyStatus:0,mraidState:void 0,getStage:function(){var a=null;for(window.event&&(a=window.event.target||window.event.srcElement);a;){if((a.id||"").indexOf("_stage")>0||a.getAttribute&&a.getAttribute("data-mid")==0)break;a=a.parentNode}return a?a:document.getElementsByClassName("MugedaStage")[0]},setMraidState:function(a){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=_mrmcp.display_mode,c=mraid.getPlacementType();this.mraidState=a.toLowerCase();var e=document.getElementById("mugeda_close_button");
switch(this.mraidState){case "default":if(b!="expand"&&c!="interstitial"&&e)e.style.display="none";typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(1);break;case "expanded":(b=="auto"||b=="expand"||b=="interstitial")&&setTimeout(function(){e.style.display="block"},50);break;case "resized":setTimeout(function(){e.style.display="block"},50)}},openLink:function(a,b){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;_mrmcp.destination_url&&_mrmcp.destination_url.indexOf("%DESTURL%")<0&&(a=
_mrmcp.destination_url);if(a){var c=a,e="ts="+(new Date).getTime();e+="&_moid="+(_mrmcp.owner_id||"");e+="&_mcid="+(_mrmcp.creative_id||"");e+="&_mw="+(_mrmcp.width||"");e+="&_mh="+(_mrmcp.height||"");e+="&_mtp="+(_mrmcp.type||"");e+="&_mtt="+encodeURIComponent(_mrmcp.title||"");var f=_mrmcp.custom_params;f&&f.indexOf("%CUSTOMPARAM%")<0&&(e+="&"+f);if((f=_mrmcp.redirect_url)&&f.indexOf("%LINK%")<0)var d=a.indexOf("?"),c=d<0?"?":"&",c=a=f+(f.lastIndexOf("=")==f.length-1?encodeURIComponent(a+c+e):"");
var g=a.split("#"),f="";g.length>1&&(f=g[1],a=g[0]);var d=a.indexOf("?"),g=d<0?"?":"&",d=d==a.length-1,j=window.location.search;if(j){for(var j=j.split("?")[1],i=j.split("&"),h=i.length,t=0;t<h;t++){var p=i[t].split("=");if(p.length==2){var k=p[1];p[0].toLowerCase()=="mugeda_click_link"&&(a=unescape(k),d=a.indexOf("?"),g=a<0?"?":"&",d=d==a.length-1)}}a+=(d?"":g)+j;d=false;j.length&&(g="&")}a+=(d?"":g)+e+(f?"#"+f:"");this.mraidReadyStatus==1?b=="internal"?mraid.open(c):b=="expand"?this.expand(c,0):
window.open(c):b=="internal"?window.location=c:b=="expand"?this.expand(c):window.open(c);MugedaTracker.fireEvent({category:"link",action:b,label:a,value:0})}},expand:function(a,b,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;if(this.mraidReadyStatus!=1){if(a&&a.length){var e=document.URL.match(/client.*preview.*id/),f=c=null;try{c=(e?window:window.parent).document,f=c.getElementById("mugeda_expanded")||c.createElement("div")}catch(d){window.open(a);return}a.match(/^(\/|http:|https:)/i)||(a=(_mrmcp.creative_path||
"")+a);f.id="mugeda_expanded";f.style.display="block";f.style.position="fixed";f.style.width=(c.defaultView.innerWidth||c.documentElement.clientWidth)+"px";f.style.height=(c.defaultView.innerHeight||c.defaultView.innerHeight)+"px";f.style.left="0px";f.style.margin="0";f.style.padding="0";f.style.border="none";f.style.top="0px";f.style.background="#000";f.innerHTML="<iframe id='mugeda_expand_iframe' src='"+a+"' style='border:none;width:100%;height:100%;margin:0px;padding:0px;'></iframe>";c.body.appendChild(f);
MugedaBehavior.processCloseButton("expand",c)}}else{var c=c||{},f=mraid.getMaxSize(),e=parseInt(c.width)||f.width,f=parseInt(c.height)||f.height,a=a||c.url,g=!a||a.length==0;b==1?(a=parseInt(c.left)||0,c=parseInt(c.top)||0,MugedaBehavior.processCloseButton("resize"),mraid.setResizeProperties({width:e,height:f,offsetX:a,offsetY:c,allowOffscreen:false}),mraid.resize()):(mraid.setExpandProperties({width:e,height:f,isModal:true,useCustomClose:_mrmcp.display_mode?true:false}),g?(mraid.expand(),MugedaBehavior.processCloseButton()):
mraid.expand(a))}},sendEmail:function(a){window.open("mailto:"+a.email_addr+"?subject="+a.email_title+"&body="+a.email_body,"_self")},savePicture:function(a){this.mraidReadyStatus==1&&mraid.supports("storePicture")&&mraid.storePicture(a.url)},addCalendarEvent:function(a){this.mraidReadyStatus==1&&mraid.supports("calendar")&&mraid.createCalendarEvent({summary:a.calendar_summary,description:a.calendar_desc,location:a.calendar_location,start:a.calendar_start_time,end:a.calendar_end_time})},createHTML5VideoTag:function(a,
b){if(a){var c="_"+ +new Date,e=0,f=0;a.data&&(c="_"+a.data.guid,a.data.param&&(e=a.data.param.continueAudio||0,f=a.data.param.clickStatus||0));var d=G("mugeda_video"+c);if(d)return d.parentNode;div=document.createElement("div");div.className="mugedaVideoHolder";div.style.margin=0;div.style.padding=0;div.style.backgroundColor="rgba(0,0,0,0)";div.style.position="absolute";div.style.top=0;div.style.left=0;div.style.width=0;div.style.height=0;div.style.zIndex=1;div.style.display="none";var g=creative_path+
"images/close_button.png",j=navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i);div.innerHTML='<video id="mugeda_video'+c+'" '+(b.video_embed?'x5-video-player-type="h5" x5-video-player-fullscreen="true"':"")+' controls playsinline x-webkit-airplay webkit-playsinline x5-playsinline preload="auto" video-id="'+b.id+'"  video-mode="'+b.mode+'" video-name="'+b.name+'"  style="width:100%;height:100%;position:absolute;z-index:2;}"></video>'+('<div id="mugeda_video_close'+c+'" align="middle" style="position: absolute;color:white;width:36px;height:36px;right:0px;top: '+
(j?0:0)+"px;cursor:pointer;background-image:url("+g+');z-index:3;"></div>');a.appendChild?a.appendChild(div):a.dom&&a.dom.appendChild(div);d=G("mugeda_video"+c);c=G("mugeda_video_close"+c);c.style.display=b.close_button?"block":"none";b.close_button&&(g=isMobile()?"touchend":"click",c.addEventListener(g,function(a){a.stopPropagation();d.src="";d.rawSrc="";d.load();div.style.display="none"},false));b.video_controls?d.setAttribute("controls","controls"):d.removeAttribute("controls");d.rawPlay=d.play;
d.rawPause=d.pause;d.play=function(){if(d.paused){if((d.src==""||d.src==window.location.href)&&d.backSrc)d.src=d.backSrc;if(d.rawSrc==""&&d.backRawSrc)d.rawSrc=d.backRawSrc;d.onplayed();d.rawPlay();Mugeda.DataStats.entry({type:"playVideo",target:d,id:d.getAttribute("video-id")});for(var a=d.parentElement;a;)if(a.className=="mugedaVideoHolder"){a.style.display="block";break}else a=a.parentElement}};d.pause=function(){d.onpaused();d.rawPause();Mugeda.DataStats.entry({type:"stopVideo",id:d.getAttribute("video-id"),
target:d})};d.onplayed=function(){if(e==0&&window.backgroundMusic)backgroundMusic.prevPlayStatus=backgroundMusic.playStatus,backgroundMusic.pause(),backgroundMusic.playStatus=0};d.onpaused=function(){if(e==0&&window.backgroundMusic&&backgroundMusic.prevPlayStatus==1)backgroundMusic.play(),backgroundMusic.playStatus=1,delete backgroundMusic.prevPlayStatus};d.onclick=function(a){a.preventDefault();a.stopPropagation();f===0?this.paused?this.play():this.pause():this.paused&&this.play()};return div}},
loadUrl:function(a){var b=a.id||(new Date).getTime(),c=a.url||"",e=a.left||0,f=a.top||0,d=isNaN(a.width)?window.aniData?window.aniData.width:320:Math.max(0,a.width),g=isNaN(a.height)?window.aniData?window.aniData.height:240:Math.max(0,a.height),j=a.before||null,i=a.style,h=a.scroll,t=a.parent,p=a.onload,k=a.onclose,m=a.position,r=a.close_position;if(!j&&!t){var q=typeof Mugeda!="undefined"&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&q&&(q=getElementOffset(q),e+=
q.left,f+=q.top)}var o=G(b);o||(o=document.createElement("div"),t?t.appendChild(o):j?j.parentNode.insertBefore(o,j):document.body.appendChild(o));o.id=b;o.style.margin=0;o.style.padding=0;o.style.backgroundColor="transparent";o.style.position=m?m:"fixed";o.style.top=0;o.style.left=0;o.style.width=0;o.style.height=0;switch(r){case "leftTop":r="left:4px;top:4px;";break;case "leftbottom":r="left:4px;bottom:4px;";break;case "rightbottom":r="right:4px;bottom:4px;";break;default:r="right: 4px;top: 4px;"}o.innerHTML=
"<iframe "+(h?"":"scrolling=no ")+'id="'+b+'_iframe" style="border:none; width:100%;height:100%; '+(h?"":"overflow:hidden;")+' " ></iframe>'+('<div id="'+b+'_iframe_close" align="middle" style="position: absolute;color:white;width: 24px;height: 24px; '+r+'cursor:pointer;background: rgba(0,0,0,0.5);border: 3px solid white;border-radius: 15px;font-family:arial;font-size: 16px;line-height:24px;">&#10006;</div>');o.style.display="none";o.style.top=f+"px";o.style.left=e+"px";o.style.width=d+"px";o.style.height=
g+"px";o.style.display="block";o.style.cssText+=i;G(b+"_iframe_close").style.display=a.close_button?"block":"none";setTimeout(function(){if(a.close_button)G(b+"_iframe_close").onclick=function(){o.style.display="none";G(b+"_iframe").src="about:blank";k&&k(o)}},100);setTimeout(function(){var a=G(b+"_iframe");a.src=c;if(p)try{a.onload=function(){p(a);a.onload=null}}catch(d){}},100);return o},playAudio:function(a,b){var c=false;if(!a||!a.audio_url||!a.audio_url.length)return false;var e=typeof Mugeda!=
"undefined"&&Mugeda.getAudioCache?Mugeda.getAudioCache(a.audio_url,a.audioId):MugedaBehavior.localCache[a.audio_url];if(e){if(e.loop=parseInt(a.audio_loop)==1?true:false,e.play)if(e.webAudio)c=e.play(a.event=="click"||b?true:false);else if(a.event=="click"){try{e.pause(),e.currentTime=0}catch(f){}setTimeout(function(){e.play()},5)}else(e.playStatus!=1||b)&&setTimeout(function(){e.play();e.playStatus=1;c=true},10)}else{var e=new Audio,d=document.createElement("source"),g=a.audio_url.lastIndexOf("."),
g=a.audio_url.substring(g+1),j=true;switch(g){case "ogg":d.type="audio/ogg";break;case "mp3":d.type="audio/mpeg";break;default:j=false,console.log("Audio extension ("+g+") not supported.")}if(j){d.src=a.audio_url;e.appendChild(d);e.autoplay=false;e.preload="auto";e.load();var i=document.getElementById("mugeda_resource_loading");if(!i)i=document.createElement("img"),i.id="mugeda_resource_loading",i.style.position="fixed",i.style.right="2px",i.style.top="2px",i.style.display="block",i.src=creative_path+
"images/loading.gif",document.body.appendChild(i);i.style.display="block";c=true;e.addEventListener("canplay",function(){i.style.display="none";e.play()},false);MugedaBehavior.localCache[a.audio_url]=e}}return c},playHTML5Video:function(a){var b=a.left||0,c=a.top||0,e=isNaN(a.width)?"100%":Math.max(0,a.width)+"px",f=isNaN(a.height)?"100%":Math.max(0,a.height)+"px",d=window.Mugeda&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&d&&!a.video_holder&&!isNaN(a.left)&&(d=
getElementOffset(d),b+=d.left,c+=d.top);var g=document.body;if(a.video_holder)if((d=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&d.scene){var g=a.video_holder,g=g.split("/"),j=a.video_object===1;if(g.length===2)d=d.scene.getObjectByName(j?g[1]:g[0]),j?(g=d?d.scene.objectHash[g[0]]:null,a.url=g?g.data.param.videoUrl:a.url):g=d?d.scene.getObjectByName(g[1]):null;else if(j){if((g=d.scene.objectHash[a.video_holder])||(g=d.scene.dom.querySelector('*[data-guid="'+a.video_holder+'"]')),g&&g.data)a.url=
g.data.param.videoUrl}else g=d.scene.getObjectByName(a.video_holder)}else{if(window.mugedaCss&&mugedaCss.magic&&(d=document.getElementById(mugedaCss.magic+"stage")))g=a.video_holder,g=g.split("/").map(function(a){return"."+a}),(g=d.querySelectorAll(g.join(" ")))&&g.length&&(g=g[0])}else g=document.body;var i=this.createHTML5VideoTag(g,a);i.style.top=c+"px";i.style.left=b+"px";i.style.width=e;i.style.height=f;i.style.display="block";var h=i.querySelector("video");h.src=a.url;h.rawSrc=a.url;h.load();
setTimeout(function(){if(a.showLoading)MugedaTools.message.show(null,{hideShade:true,parent:i,center:true}),h.loadingShown=true,h.ontimeupdate=function(){if(h.loadingShown)MugedaTools.message.close(),h.loadingShown=false};a.event=="appear"&&(window.WeixinJSBridge?WeixinJSBridge.invoke("getNetworkType",{},function(){h.play();h.playing=true},false):document.addEventListener("WeixinJSBridgeReady",function(){WeixinJSBridge.invoke("getNetworkType",{},function(){h.play();h.playing=true})},false));h.play();
h.playing=true},10)},playVideo:function(a){a=a||{};if(!a.video_url)return false;if(this.mraidReadyStatus!=1){var b=a.dom||document.querySelector('video[video-id="'+a.video_id+'"]');a.video_mode=="object"&&a.video_id&&b&&b.rawSrc==a.video_url||this.playHTML5Video({url:a.video_url,id:a.video_id||"",name:a.video_name||"",mode:a.video_mode||"",video_object:parseInt(a.video_object,10),video_holder:a.video_holder,left:parseInt(a.video_left,10),top:parseInt(a.video_top,10),width:parseInt(a.video_width,10),
height:parseInt(a.video_height,10),close_button:parseInt(a.video_close,10)==1,video_controls:parseInt(a.video_controls,10)==1,video_embed:parseInt(a.video_embed,10)==1,auto:parseInt(a.video_autoplay,10)==1,event:a.event})}else mraid.playVideo(a.video_url)},stopVideo:function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),b=0,c=a.length;b<c;b++){var e=a[b].querySelector("video");if(e)e.backSrc=e.src,e.backRawSrc=e.rawSrc,e.src="",e.rawSrc="",e.load();a[b]&&(a[b].style.display="none")}},
controlVideo:function(a,b){var c=document.querySelector("#mugeda_video_"+a);if(c)if(b=="play")c.play();else if(b=="pause")c.pause();else{if(b=="stop")c.pause(),c.currentTime=0}else if((c=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&c.scene)if(c=c.scene.objectHash[a]){var e=c.data.param;b==="play"&&MugedaMraid.playVideo({auto:e.videoAutoPlay,clickStatus:e.clickStatus,event_name:"",hidePlayIcon:e.hidePlayIcon,video_close:0,video_continue_audio:e.continueAudio,video_controls:e.hidePlayControls==
1?0:1,video_holder:c.data.guid,video_left:0,video_mode:"object",video_name:e.name,video_embed:e.embedVideo,video_object:1,video_top:0,video_url:e.videoUrl})}},sendShortMessage:function(a){var b="sms:"+a.phone_number;if(a.sms_body){var c=navigator.userAgent.toLowerCase().indexOf("android")>-1;b+=(c?"?":"&")+"body="+a.sms_body}window.open(b,"_self")},makePhoneCall:function(a){window.open("tel:"+a.phone_number,"_self")}};
Mugeda.getContentId=function(){var a="",b=0;if(_mrmcp.creative_id)a=_mrmcp.creative_id,_mrmcp.previewMode&&(b=3);else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)a=Mugeda.data.crid,b=3;if(a==""&&/\/edit\/(\w+)\&?/.test(top.location.href))a=RegExp.$1,b=a.length<16?1:2;else if(a==""&&/id=(\w+)\&?/.test(window.location.search))b=3,a=RegExp.$1;return{crid:a,mode:b}};
MugedaBehavior={localCache:{},shakeHash:{},pause:function(){typeof Mugeda!="undefined"&&Mugeda.pause&&Mugeda.pause()},resume:function(a){typeof Mugeda!="undefined"&&Mugeda.resume&&Mugeda.resume(a)},nextPage:function(){typeof Mugeda!="undefined"&&Mugeda.nextPage&&Mugeda.nextPage()},prevPage:function(){typeof Mugeda!="undefined"&&Mugeda.prevPage&&Mugeda.prevPage()},gotoPage:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoPage&&Mugeda.gotoPage(a)},disablePage:function(){typeof Mugeda!="undefined"&&
Mugeda.disablePage&&Mugeda.disablePage()},enablePage:function(){typeof Mugeda!="undefined"&&Mugeda.enablePage&&Mugeda.enablePage()},next:function(){typeof Mugeda!="undefined"&&Mugeda.next&&Mugeda.next()},previous:function(){typeof Mugeda!="undefined"&&Mugeda.previous&&Mugeda.previous()},gotoAndPlay:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(a)},gotoAndStop:function(a){gotoAndPause(a)},gotoAndPause:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPause&&Mugeda.gotoAndPause(a)},
callback:function(a,b){var c=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null,e=null;c&&(e=c.getCallback(b.name));!e&&window&&b.name&&b.name.length&&window[b.name]&&(e=window[b.name]);e&&e(a,b.key,b.value)},map:function(a){var b=a.map_key.replace(/(\n|\r)/g,"+"),c=void 0;if(a.map_address){var c=a.map_address.replace(/(\n|\r)/g,"+"),e=navigator.userAgent.toLowerCase().indexOf("android")>-1,f=parseInt(a.map_type,10),d=function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),b=0,c=
a.length;b<c;b++)a[b]&&(a[b].style.display="none");(a=G("mugedaMap-mask"))?g(1):(a=document.createElement("div"),b=creative_path+"images/loading.gif",a.id="mugedaMap-mask",a.className="mugedaMapControl",a.innerHTML='<p id="mugedaMap-title"><a id="mugedaMap-back">返回</a>位置信息</p><div id="mugedaMap-con"></div><div id="mugedaMap-loading"><div class="spinner"></div><style>.smnoprint {top: 70px!important;}.BMap_stdMpCtrl {top: 70px!important;}.BMap_stdMpCtrl.BMap_stdMpType1.BMap_noprint.anchorTR {top: 80px!important;}.BMap_noprint.anchorTR {display: none!important;}.amap-toolbar {right: 10px!important; bottom: 10px!important;left: auto!important; top: auto!important;}.mugedaMapControl {position:absolute;left:0;top:0;height:100%;width:100%;z-index:999;}.mugedaMapMaskVisible {-webkit-transition:transform 1s;transform:translate3d(-100%, 0, 0);-webkit-transform:translate3d(-100%, 0, 0);}.mugedaMapControl #mugedaMap-title {position:fixed;height:44px;line-height:44px;width:100%;text-align:center;z-index:1;background:rgba(255,255,255,.8);margin:0;}.mugedaMapControl #mugedaMap-con {height:100%;width:100%;}.mugedaMapControl #mugedaMap-back {position:absolute;left:5px;display:inline-block;height:100%;width:40px;cursor:pointer;}.mugedaMapControl #mugedaMap-loading {position:absolute;width:100%;height:100%;line-height:100%;left:0;top:44px;display:none;background:#fff;z-index:2;}.mugedaMapControl .spinner {position:absolute;width:20px;height:30px;left:50%;top:50%;margin:-50px 0 0 -10px;background-image:url('+
b+');background-repeat:no-repeat;background-size:contain;}.mugedaMapControl .spinner:after {content: "加载中 ...";position:absolute;width:80px;left:-25px;top:120%;}</style>',document.body.appendChild(a),(a=G("mugedaMap-back"))&&a.addEventListener("click",function(a){a.stopPropagation();g(0)},false))},g=function(a){var b=G("mugedaMap-mask");b&&b.classList.toggle("mugedaMapMaskVisible",!a)},j=function(a){var b=G("mugedaMap-loading");if(b)b.style.display=a?"block":"none"},i,h,t=function(a,
b,c,d){i||(i=new BMap.Map("mugedaMap-con"));i.addControl(new BMap.MapTypeControl({mapTypes:[BMAP_NORMAL_MAP,BMAP_HYBRID_MAP]}));var c=new BMap.NavigationControl,e=new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_RIGHT,type:BMAP_NAVIGATION_CONTROL_SMALL});i.addControl(c);i.addControl(e);h||(h=new BMap.LocalSearch(i,{renderOptions:{map:i,autoViewport:true},onSearchComplete:function(a){typeof d==="function"&&d.call(i,a)}}));b&&a?h.searchNearby(b,a):h.search(b)},p,k=function(a,b){console.log(a,b);p||
(p=new AMap.Map("mugedaMap-con",{resizeEnable:true,zoom:3}));AMap.plugin(["AMap.ToolBar","AMap.PlaceSearch","AMap.CitySearch"],function(){var c=new AMap.ToolBar;p.addControl(c);(new AMap.PlaceSearch({city:a})).search(b,function(a,b){console.log(b);if(b.poiList.pois.length){for(var c=b.poiList.pois,d=0;d<c.length;d++){var e=c[d],g=[];g[d]=new AMap.Marker({position:e.location,title:e.name});p.add(g[d])}p.setFitView()}else Mugeda.messageBox("抱歉，没有搜索到相关信息",
"alert")})})};window.buildTengxunMap=function(){if(!d)var a=new qq.maps.LatLng(39.916527,116.397128),d=new qq.maps.Map(document.getElementById("mugedaMap-con"),{center:a,zoom:6,mapTypeControlOptions:{mapTypeIds:[qq.maps.MapTypeId.ROADMAP,qq.maps.MapTypeId.SATELLITE,qq.maps.MapTypeId.HYBRID],position:qq.maps.ControlPosition.BOTTOM_CENTER}});var e=new qq.maps.LatLngBounds,g=[],a=new qq.maps.SearchService({complete:function(a){for(var a=a.detail.pois,b=0,c=a.length;b<c;b++){var f=a[b];e.extend(f.latLng);
f=new qq.maps.Marker({map:d,position:f.latLng});f.setTitle(b+1);g.push(f)}d.fitBounds(e)}});a.setLocation(c);a.search(decodeURIComponent(b))};var m=function(a,b,c){if(f===0){var e=["//api.map.baidu.com/api?v=3.0&ak=FOm6cLbES9zjrtvcDYndkwSR","//api.map.baidu.com/getscript?v=3.0&ak=FOm6cLbES9zjrtvcDYndkwSR"],b=decodeURIComponent(b),a=decodeURIComponent(a);d();j(1);for(var g=0,h=0,i=e.length;h<i;h++)c=document.createElement("script"),c.src=e[h],c.onload=function(){++g===i&&t(a,b,"",function(a){a.getNumPois()===
0&&Mugeda.messageBox("抱歉，没有搜索到相关信息","alert");j(0)})},document.head.appendChild(c)}else if(f===1)if(h="https://maps.google.com/maps?q="+(a+""+(b.length?"+near+"+b:""))+"&z=12",e=parseFloat((""+(/CPU.*OS ([0-9_]{1,5})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||[0,""])[1]).replace("undefined","3_2").replace("_",".").replace("_",""))||false,c==1){if(c=document.getElementById("aMugedaGeoLocation"))c.href=h,h=document.createEvent("HTMLEvents"),
h.initEvent("click",true,true),c.dispatchEvent(h)}else e&&e<6?window.location.href=h:window.open(h,"_blank");else if(f===2){e=["//webapi.amap.com/maps?v=1.4.15&key=189d47fd622309f74807543767b6cf5f"];d();j(1);h=g=0;for(i=e.length;h<i;h++)c=document.createElement("script"),c.src=e[h],c.onload=function(){++g===i&&(k(decodeURIComponent(b),decodeURIComponent(a)),j(0))},document.head.appendChild(c)}else if(f===3){e=["//map.qq.com/api/js?v=2.exp&key=Q2XBZ-BQ56F-6DCJD-NIGR5-65MDQ-FCBJG&callback=buildTengxunMap"];
d();j(1);h=g=0;for(i=e.length;h<i;h++)c=document.createElement("script"),c.src=e[h],c.onload=function(){++g===i&&j(0)},document.head.appendChild(c)}};if(!e&&c.length==0&&navigator.geolocation){a=document.getElementById("aMugedaGeoLocation");if(!a)a=document.createElement("a"),a.id="aMugedaGeoLocation",a.style.display="none",a.href="",a.target="_blank",document.body.appendChild(a);navigator.geolocation.getCurrentPosition(function(a){c=a.coords.latitude+","+a.coords.longitude;m(b,c,1)})}else m(b,c)}else Mugeda.messageBox("未设置地址，请在行为里进行设置。",
"alert")},popupForm:function(a,b){function c(a,b){if(a&&b)return a.querySelector("#"+b)}function e(a){if(window.localStorage&&window.localStorage.getItem)return unescape(localStorage.getItem(a)||"");var b,c,d,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(c=e[b].substr(0,e[b].indexOf("=")),d=e[b].substr(e[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a.toLowerCase())return unescape(d);return""}function f(a,b){if(window.localStorage&&window.localStorage.getItem)try{localStorage.setItem(a,
escape(b))}catch(c){console.info("Oops, localStorage full"),localStorage.clear(),localStorage.setItem(a,escape(b))}else{var d=new Date;d.setDate(d.getDate()+3);d=escape(b)+"; expires="+d.toUTCString();document.cookie=a.toLowerCase()+"="+d}}function d(a){var b=document.querySelector(".MugedaStage")?null:G("viewbox")||G("frame");if(b)b.style.display=a?"":"none";return b?true:false}function g(a){if(b){var c=function(a,b){Array.prototype.forEach.call(a,function(a,c){b(a,c)})};c(a.querySelectorAll(".popupFormInputBox input,.popupFormInputBox textarea"),
function(a){a.value=""});c(a.querySelectorAll(".popupFormRadioList input,.popupFormCheckbox input"),function(a){a.checked=false});c(a.querySelectorAll(".popupFormSelectList select"),function(a){a.value=a.querySelector("option").getAttribute("value")})}else if(c=a.querySelector("form"),c.style.bottom=-c.offsetHeight+"px",a.style.background="rgba(0,0,0,0)",setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},500),d(1)&&(document.body.style.overflowY="hidden",isMobile()))document.body.style.height=
"100%"}var j=a.openTarget=="default"||a.openTarget=="frame"||a.openTarget=="page";if(a&&!(a.openTarget=="callback"&&!a.callback||a.openTarget!="callback"&&a.openTarget!="customizable"&&!j&&!a.url)){var j=document.documentElement.clientWidth,i=document.documentElement.clientHeight,h=[],t=function(b,c){var c=c||{},d=c.detail,e=c.form||(d?d.form:null),d={item:d,form:e,title:a.title,hideItem:function(a){e&&e.elements[a]&&(e.elements[a].parentNode.style.display="none")},showItem:function(a){e&&e.elements[a]&&
(e.elements[a].parentNode.style.display="block")}},c=document.createEvent("Events");c.initEvent(b,true,true);c.detail=d;window.dispatchEvent(c)};window.addEventListener("_mugedaFormChanged",function(a){t("mugedaFormChanged",a)});var p=a.items||[];window.popupFormFields=p;if(!a.html){var k="";b?(k+='<div class="popupFormContent">',a.title&&(k+='<div align="center" class="popupFormTitle"><h2>'+a.title+"</h2></div>")):(k+='<div align="center" class="popupFormTitle">',k+='<div class="title-col-2" align="center"><input type="button" value="'+
a.cancelName+'" class="popupFormCancel" id="popupFormCancel"></div>',k+='<div class="title-col-6" align="center"><h2>'+(a.title||"&nbsp;")+"</h2></div>",k+='<div class="title-col-2" align="center"><input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>',k+="</div>",k+='<div class="popupFormContent">');var m=navigator.userAgent.toLowerCase(),r=m.indexOf("android")>-1,q=parseFloat(m.slice(m.indexOf("android")+8)),o="",y=0,z={phone:"tel",input:"text"};r&&q<3&&(o=
"-webkit-transform: scale(2,2);-webkit-transform-origin:center center;");for(var A=b?"":":",m=0;m<p.length;m++){var l=p[m],x=(l.value||"").trim();if(x){for(var x=x.split("\n"),u=[],v=0;v<x.length;v++){var I=x[v].split("("),B=I[0],I=(I[1]||"").replace(/\)$/,"")||B,F=["FORMID",I,m,v].join("_");u[v]={id:F,text:B,value:I}}x=u}F='id="popupFormField_'+m+'"';switch(l.type){case "radio":k+="<div "+F+' class="popupFormRadioList">';l.description&&(k+='<label class="inputlabel">'+l.description+(l.required?"*":
"")+A+"</label>");k+='<div class="mformradio">';for(v=0;v<x.length;v++)u=x[v],B=e(u.id),k+='<label><input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="radio" name="'+l.id+'" value="'+u.value+'" id="'+u.id+'" '+(B=="true"?"checked=checked":"")+" ><span "+(v==x.length-1?"":" style='border-right:1px solid "+a.background+"'")+">"+u.text+"</span></label>",h[u.id]=u.id;k+="</div></div>";
break;case "checkbox":k+="<div "+F+' class="popupFormCheckbox">';l.description&&(k+='<label class="inputlabel">'+l.description+(l.required?"*":"")+A+"</label>");k+='<div class="mformcheck">';k+=l.rangeType==="vertical"?"<table>":"";for(v=0;v<x.length;v++)u=x[v],B=e(u.id),k+=l.rangeType==="vertical"?'<tr><td><input type="checkbox" value="'+u.value+'" id="'+u.id+'" '+(B=="true"?"checked=true":"")+' ></td><td><label for="'+u.id+'" >'+u.text+"</label></td></tr>":'<input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="checkbox" name="'+
l.id+'" value="'+u.value+'" id="'+u.id+'" '+(B=="true"?"checked=true":"")+' ><label for="'+u.id+'" >'+u.text+"</label>",h[u.id]=u.id;r&&q<3&&l.rangeType!="vertical"&&(y=6);k+=l.rangeType==="vertical"?"</table>":"";k+="</div></div>";break;case "select":k+="<div "+F+' class="popupFormSelectList">';l.description&&(k+='<label class="inputlabel text">'+l.description+(l.required?"*":"")+A+"</label>");k+='<select class="text" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" name="'+
l.id+'" id="'+("_map_"+l.description)+'">';k+='<option value="">'+l.description+"</option>";B=e(l.description);for(v=0;v<x.length;v++)u=x[v],k+='<option value="'+u.value+'" '+(B==u.value?"selected=selected":"")+">"+u.text+"</option>";k+="</select>";k+="</div>";h[l.description]="_map_"+l.description;break;case "textarea":k+="<div "+F+' class="popupFormInputBox">';k+='<label class="inputlabel inputlabel_area">'+l.description+(l.required?"*":"")+A+'</label><textarea name="'+l.id+'" id="_mcp_'+escape(l.description)+
'" rows="4" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" style="resize:none; height:48px;">'+(l.value.length?l.value:e(l.description))+"</textarea>";k+="</div>";h[l.description]="_mcp_"+escape(l.description);break;default:k+="<div "+F+' class="popupFormInputBox">',k+='<label class="inputlabel text">'+l.description+(l.required?"*":"")+A+'</label><input class="text" name="'+l.id+'" id="_mcp_'+
escape(l.description)+'" type="'+(z[l.type]||l.type)+"\" onchange=\"var event = document.createEvent('Events');event.initEvent('_mugedaFormChanged', true, true);event.detail = this;window.dispatchEvent(event);\" value=\""+(e(l.description)||l.value)+'" '+(b?'placeholder="'+l.description+'"':"")+">",k+="</div>",h[l.description]="_mcp_"+escape(l.description)}}b&&(k+='<div class="popupFormBtn"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel">',k+='<input id="actionButton" type="button" value="'+
a.submitName+'" class="popupFormSubmit"></div>');k+="</div>";a.html=k}delete this.popupFormDiv;var n=this.popupFormDiv;if(!n){m=function(c){var c=c||".popupForm",d=1;if(/^rgba\(\d+,\s\d+,\s\d+,\s([0-9.]+)\)$/.exec(a.background))d=RegExp.$1;d="<style>"+c+" {width:100%;font-size:"+a.fontSize+'px;font-family:Tahoma,"微软雅黑",Arial, SimHei;}'+c+' * {font-family:Tahoma,"微软雅黑",Arial, SimHei;}'+c+" form{position:absolute;width:100%;background-color:"+a.background+";}"+
c+" *{margin:0;box-sizing:border-box;-webkit-appearance: none; -moz-appearance: none; appearance: value;}"+c+" .inputlabel{width:33%;height:28px;font-size:"+a.fontSize+"px;line-height:28px;display:inline-block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:top;color:#000;}"+c+" span{color:#333;}"+c+" label{color:#000;}"+c+" #popupFormField_0{padding-top:16px;}"+c+" .popupFormMask {position:absolute;left:0;top:0;width:100%;height:100%;background-color: "+a.background+"}"+
c+" .popupFormContent {padding-bottom:16px; background-color:#fff;opacity:"+d+";}"+c+" .popupFormTitle {width:100%;padding:20px 0;overflow:hidden;background-color: "+a.background+"}"+c+" h2 {font-weight:normal;font-size:"+(2+parseInt(a.fontSize))+"px;color:"+a.color+";}"+c+" h3{text-align:left;font-size:"+a.fontSize+"px; font-weight: normal;color:"+a.color+";}"+c+" .popupFormInputBox{padding:8px 16px;text-align:left;}"+c+" .popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select{width:67%;height:28px;border:1px solid "+
a.background+";font-size:"+a.fontSize+"px;padding:0;padding-left:8px;vertical-align:top;border-radius:2px;}"+c+" .popupFormSelectList{padding:8px 16px 0;}"+c+" .popupFormRadioList{padding:8px 16px 0;}"+c+" .popupFormCheckbox{padding:8px 16px 0;}"+c+" .popupFormTitle input{border-width:0;cursor:pointer;font-size:"+a.fontSize+"px;color:"+a.color+"}"+c+" .popupFormSubmit{border:none;background:none}"+c+" .popupFormCancel{background:none;border:none;}"+c+" .popupFormRadioList input{margin:0 5px 0 8px;}"+
c+" .popupFormRadioList label{vertical-align:top;}"+c+" .mformradio {background-color:#EFEFEF;border:1px solid "+a.background+";overflow:hidden;display:inline-block;}"+c+" .mformradio label{float:left; min-width:48px;position:relative;}"+c+" .mformradio label span{text-align:center;padding:6px 8px;display:block;}"+c+" .mformradio label input{position:absolute;width:100%;height:100%;margin:0;border:0;opacity:0;}"+c+" .mformradio input:checked + span{background-color:"+a.background+";color:#F7F7F7;}"+
c+" .mformcheck{margin:0 0 8px;display:inline-block;}"+c+" .mformcheck input{"+o+"width:24px;height:24px;background-color:#EFEFEF;border:1px solid "+a.background+";vertical-align:middle;margin:3px 2px;}"+c+" .mformcheck input:checked{background-color:"+a.background+";}"+c+" .popupFormTitle .title-col-2 {float:left;width:20%;padding:0 ;text-align:center;}"+c+" .popupFormTitle .title-col-6 {float:left;width:60%;padding:0 ;}"+c+" .popupFormTitle .title-col-2 input {font-size:"+(2+parseInt(a.fontSize))+
"px;}"+c+" .mformcheck label{vertical-align:"+y+"px;font-size:"+a.fontSize+"px;padding-top:0;padding-left:4px;padding-right:8px;}";b&&(d+=c+" .popupFormBtn {width:100%;padding:20px 0 0 0;text-align:center;}",d+=c+" .popupFormSubmit {width:90px;height:30px;color:"+a.color+";background-color:"+a.background+"}",d+=c+" .popupFormCancel {width:90px;height:30px;margin-right:15px;color:"+a.color+";display:none;background-color:"+a.background+"}");d+="</style>";return d};if(!n){var J=a.openTarget=="backend"?
"popupFormIframe":"_"+a.openTarget,n=document.createElement("div");n.style.display="none";n.className=b?"popupForm2":"popupForm";var C="";if(b)var D=function(b){for(var c={l:48,r:200},d=0,e=0,g=b.length;e<g;e++){for(var f=b[e],j=f.description.length,h=0,i=0;i<j;i++)h+=f.description[i].match(/[㐀-龿]/)?2:1;d=Math.max(d,h)}d=d>8?8:d;b=a.fontSize*(d-4);d>4&&d<=8&&(c.l+=b,c.r-=b);return c}(p),C=m(".popupForm2");else C=m();n.innerHTML='<form method="'+a.method+'" target="'+J+'" autocomplete="on"></form><iframe name="popupFormIframe" id="popupFormIframe" style="display:none"></iframe>'+
C;!b&&!a.isCss?document.body.appendChild(n):(a.hwObj=D,a.iframeDiv=n,a.parentDom&&a.parentDom.appendChild(a.iframeDiv));this.popupFormDiv=n;n.form=n.childNodes[0];n.form.onclick=function(){};self=this;b||n.addEventListener(isMobile()?"touchend":"mouseup",function(a){if(!window.cardFrame){if(a.target==n)g(n),self.popupFormDiv=null,a.stopPropagation();var b=a.target.nodeName.toLowerCase(),c=(a.target.type||"").toLowerCase();["input","textarea","select"].indexOf(b)>=0&&c!="checkbox"&&c!="submit"&&(a.target.focus(),
r&&setTimeout(function(){a.target.scrollIntoView();a.target.scrollIntoViewIfNeeded&&a.target.scrollIntoViewIfNeeded()},500),a.stopPropagation());c=="button"&&a.stopPropagation()}});C=function(){function d(){var e=[],f=p;if(!b)f=window.popupFormFields;for(var j=0;j<f.length;j++){var h=f[j],i=c(n,"popupFormField_"+j),k="",l=i.querySelectorAll("select");l.length==0&&(l=i.querySelectorAll("textarea"),l.length==0&&(l=i.querySelectorAll("input")));if(l.length==1)k=l[0].value||"";else if(l.length>1){for(var k=
[],m=0;m<l.length;m++)if(i=l[m],i.checked&&(k.push(i.value),i.type=="radio"))break;k=k.join(",")}if(h.required&&!k){Mugeda.messageBox((h.description||"item")+" required");l[0].focus();return}if(k)switch(h.type){case "phone":if(!/^\d+$/.test(k)){Mugeda.messageBox((h.description||"Phone number")+" required");l[0].focus();return}break;case "email":if(!/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(k)){Mugeda.messageBox((h.description||"Email")+" required");l[0].focus();return}}a.openTarget==="default"?
e.push(encodeURIComponent(h.description+"("+h.id+")")+"="+encodeURIComponent(k||"")):e.push(encodeURIComponent(h.id)+"="+encodeURIComponent(k||""))}if("popupFormIframe"==J)G("actionButton").value=a.pendingName;e=e.join("&");f=a.url+"?"+e;a.loadFinished=function(){g(n);self.popupFormDiv=null};if(a.openTarget=="customizable")f={callback:function(b){a.msg?Mugeda.messageBox(a.msg,"alert",function(){window.open(b,"_self")}):window.open(b,"_self")},cancel:false},window.MugedaCard&&MugedaCard.finalizeCustomParameters&&
MugedaCard.finalizeCustomParameters(e,f),a.loadFinished();else if(a.openTarget=="default"||a.openTarget=="page"||a.openTarget=="frame"||a.openTarget=="callback"){f=0;j=_mrmcp.creative_id||"";_mrmcp.previewMode&&(f=3);if(j==""&&Mugeda&&Mugeda.data&&Mugeda.data.crid)j=Mugeda.data.crid;if(j==""&&/\/edit\/(\w+)\&?/.test(top.location.href))j=RegExp.$1,f=j.length<16?1:2;else if(j==""&&/id=(\w+)\&?/.test(window.location.search))f=3,j=RegExp.$1;h=function(a,b,c){var c=c||"post",d=document.createElement("form"),
e=document.createElement("iframe");d.setAttribute("method",c);d.setAttribute("action",a);a="__iframe"+Math.random()*1E4;e.setAttribute("id",a);e.setAttribute("name",a);d.setAttribute("target",a);e.style.width=0;e.style.height=0;e.style.display="none";e.addEventListener("load",function(){});a=0;for(c=b.length;a<c;a++){var g=b[a].split("="),f=g[0],g=g[1],j=document.createElement("input");j.setAttribute("type","hidden");j.setAttribute("name",f);j.setAttribute("value",g);d.appendChild(j)}document.body.appendChild(d);
document.body.appendChild(e);d.submit()};j&&/^[a-zA-Z0-9\-\_\.]+\.(mugeda|mgd5|h5mc|h5mgd|imugeda|mgdh5|hubpd)\.com$/.test(window.location.hostname)&&(l=_mrmcp.saveFormUrl||"//weika.mugeda.com/server/cards.php/saveform",/_mrcmc=(.*?)(\&|$|\#)/.test(location.search)&&(e+="&_mrcmc="+RegExp.$1),/_mrcsc=(.*?)(\&|$|\#)/.test(location.search)&&(e+="&_mrcsc="+RegExp.$1),e+="&_msuid="+getMsuid(),h(l,(e+"&crid="+j+"&mode="+f).split("&")),a.msg&&Mugeda.messageBox(a.msg));a.openTarget=="callback"?a.callback&&
window[a.callback]?(f={callback:function(){a.msg&&Mugeda.messageBox(a.msg)},cancel:false},window[a.callback](e,f),MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0}),f.cancel!==true&&f.callback()):console.log("No callback function found. Skipping..."):a.openTarget=="frame"?a.callback&&a.callback():a.openTarget=="page"&&a.callback&&a.callback();a.loadFinished()}else try{window.open(f,J),G("popupFormIframe").onload=function(){a.loadFinished();MugedaTracker.fireEvent({category:"interaction",
action:"form",label:"",value:a.id?parseInt(a.id,36):0});a.msg&&Mugeda.messageBox(a.msg)}}catch(o){a.loadFinished(),Mugeda.messageBox("Form submission failed. Please try again. ")}}n.querySelector("#popupFormIframe").onload=null;for(l in h){var e=document.getElementById(h[l]);e&&(e.type=="checkbox"||e.type=="radio"?f(l,e.checked):f(l,e.value))}q<3?d():setTimeout(d,200);return false}}n.style.display="";n.form.innerHTML=a.html;if(a.id)n.form.id=a.id;var K=isMobile()?"touchstart":"click";n.form.querySelector("input[id=actionButton]").addEventListener(K,
C,false);n.style.display="";n.style.visibility="hidden";setTimeout(function(){t("mugedaFormInitialized",{form:n.form});n.style.visibility="visible"},200);setTimeout(function(){c(n,"popupFormCancel").addEventListener(K,function(){g(n);self.popupFormDiv=null},false)},500);D=n.querySelectorAll(".popupFormInput");for(m=0;m<D.length;m++)C=D[m],C.onfocus=onInputFocus,C.onblur=onInputBlur;var w;a.target?w=a.target.getBoundingClientRect():(D=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&a.isCss?
(j=D.adaption,w={left:Math.max(0,(window.Mugine?1:-1)*j.marginLeft),top:window.Mugine?0:Math.max(0,(window.Mugine?1:-1)*j.marginTop),width:Math.min(j.width,D.width),height:Math.min(j.height,D.height)}):w={left:0,top:0,width:j,height:i};document.body.style.overflowY="auto";if(d()){if(n.style.marginLeft=Math.max(2,w.left+document.documentElement.scrollLeft+(w.width-n.offsetWidth)/2)+"px",n.style.marginTop=Math.max(2,w.top+document.documentElement.scrollTop+(w.height-n.offsetHeight)/2)+"px",n.style.marginBottom=
"32px",n.offsetHeight+32>document.documentElement.scrollHeight&&(n.style.marginTop=parseInt(window.getComputedStyle?getComputedStyle(n).marginTop:n.currentStyle.marginTop)+32+"px",isMobile()))document.body.style.height=n.offsetHeight+64+"px"}else if(n.style.position="relative",n.style.left=w.left+"px",n.style.top=w.top+"px",Math.max(2,w.top+(w.height-n.offsetHeight)/2),Math.max(2,w.left+(w.width-n.offsetWidth)/2),!b){var H=n.querySelector("form");H.style.bottom="-9999px";n.style.overflow="hidden";
setTimeout(function(){n.style.background="rgba(0,0,0,0)";n.style.width=w.width+"px";n.style.height="100%";H.style.webkitTransition="none";H.style.bottom=-H.offsetHeight+"px";setTimeout(function(){H.style.webkitTransition="all 500ms";H.style.bottom="0px";H.style.overflowY="auto";!b&&(n.style.background="rgba(0,0,0,0.3)")},1)},1)}}}},getPopupFormHeight:function(a){for(var b=a.items,c=0,e=0,f=b.length;e<f;e++){var d=b[e];switch(d.type){case "input":case "phone":case "email":c+=44;break;case "textarea":c+=
64;break;case "radio":c+=48;break;case "checkbox":d=d.value.split("\n").length;c+=32*d+8;break;case "select":c+=36;break;default:c+=44}}a.title&&(c+=60);c+=8;c+=50;c+=16;return c},processAction:function(a,b,c,e){var f=true;if(a.type=="pause")this.pause(a.param);else if(a.type=="play")this.resume(1);else if(a.type=="next")this.next();else if(a.type=="previous")this.previous();else if(a.type=="nextPage")this.nextPage();else if(a.type=="prevPage")this.prevPage();else if(a.type=="disablePage")this.disablePage();
else if(a.type=="enablePage")this.enablePage();else if(a.type=="gotoPage"){var d=a.param&&a.param.page_number?a.param.page_number:a.param,g=typeof d=="string"?d.split(";"):[];g.length>1&&(d=g[Math.floor(Math.random()*g.length)]);d=parseInt(d);this.gotoPage(d)}else if(a.type=="callback")this.callback(a.object,a.param);else if(a.type=="map")this.map(a.param);else if(a.type=="gotoAndPlay")d=a.param&&a.param.frame_number?a.param.frame_number:a.param,g=typeof d=="string"?d.split(";"):[],g.length>1&&(d=
g[Math.floor(Math.random()*g.length)]),d=parseInt(d),isNaN(d)&&(d=a.param&&a.param.frame_name?a.param.frame_name:"",d=Mugeda.mapFrameNameId[d],d=parseInt(d)+1),this.gotoAndPlay(d);else if(a.type=="gotoAndPause"||a.type=="gotoAndStop")d=a.param&&a.param.frame_number?a.param.frame_number:a.param,g=typeof d=="string"?d.split(";"):[],g.length>1&&(d=g[Math.floor(Math.random()*g.length)]),d=parseInt(d),isNaN(d)&&(d=a.param&&a.param.frame_name?a.param.frame_name:"",d=Mugeda.mapFrameNameId[d],d=parseInt(d)+
1),this.gotoAndPause(d);else if(a.type=="call")MugedaMraid.makePhoneCall(a.param);else if(a.type=="sms")MugedaMraid.sendShortMessage(a.param);else if(a.type=="email")MugedaMraid.sendEmail(a.param);else if(a.type=="video")a.param.event=b,MugedaMraid.playVideo(a.param);else if(a.type=="stopVideo")MugedaMraid.stopVideo(a.param);else if(a.type=="audio")a.param.event=b,f=a.restart,window.Mugeda&&Mugeda.getMugedaObject&&(b=Mugeda.getMugedaObject(),d=Math.floor(b.scene.currentId),a.unit&&a.unit.frameStart==
d&&(f=true)),f=MugedaMraid.playAudio(a.param,f);else if(a.type=="picture")MugedaMraid.savePicture(a.param);else if(a.type=="calendar")MugedaMraid.addCalendarEvent(a.param);else if(a.type=="expand")MugedaMraid.expand(a.param.url,0,a.param);else if(a.type=="resize")MugedaMraid.expand("",1,a.param);else if(a.type=="stopAudio")Mugeda.stopAudio&&Mugeda.stopAudio(a.param);else if(a.type=="stopAllAudio")Mugeda.stopAudioAll&&Mugeda.stopAudioAll();else if(a.type=="submitForm"){var j=a.param,b=a.mugeda,g=j.submit_object,
j=(j.submit_target||0)==0?_mrmcp.saveFormUrl||"//weika.mugeda.com/server/cards.php/saveform":j.submit_url,i="",h=0;if(_mrmcp.creative_id)i=_mrmcp.creative_id,_mrmcp.previewMode&&(h=3);else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)i=Mugeda.data.crid,h=3;if(i==""&&/\/edit\/(\w+)\&?/.test(top.location.href))i=RegExp.$1,h=i.length<16?1:2;else if(i==""&&/id=(\w+)\&?/.test(window.location.search))h=3,i=RegExp.$1;if(i&&g){for(var g=g.split(","),i="crid="+i+"&mode="+h,h={},t=0,p=0;p<g.length;p++){var k=g[p]||
"",m=k.split("_"),r;if(m&&m.length>1){var q=b.scene.getObjectByName(m[0]);q&&(r=q.scene.getObjectByName(m[1]))}else r=b.scene.getObjectByName(k);if(r)if(r.data.type===2041){if(d=r.data.param.name)if(m=r.data.param.required,k=r.dom.querySelector("input:checked"),m===1&&!k){Mugeda.messageBox("请选择【"+d+"】，该项不能为空。");return}else h[d]=k?k.value:"",t++}else if(r.data.type===2038){if(d=r.data.param.name)if(m=r.data.param.required,k=document.querySelectorAll('input[name="'+
d+'"]:checked'),m===1&&!k.length){Mugeda.messageBox("请选择【"+d+"】，该项不能为空。");return}else{for(var m=[],q=0,o=k.length;q<o;q++)m.push(k[q].value);h[d]=m.length?m.join(","):"";t++}}else if(r.data.type===2039)if(m=r.data.param.required,q=unescape(r.data.param.textContent),o=r.dom.querySelector("option:checked"),m===1&&o&&o.innerText===q){Mugeda.messageBox("请选择【"+(r.data.param.name||"下拉列表")+"】，该项不能为空。");
return}else i+=o?"&"+k+"="+(o.value!==q?o.value:""):"&"+k+"=",t++;else{q=r?r.text||"":"";q.indexOf("#")&&(q=q.replace(/\#/g,""));var o=r.data.param.inputType,y={tel:"^[1][3,4,5,6,7,8,9][0-9]{9}$",email:'^(([^<>()\\[\\]\\\\.,;:\\s@"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@"]+)*)|(".+"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$',date:"",time:"",number:"^\\d+$"},m=r.data.param.required;if(m===1&&!q.length){Mugeda.messageBox("请选择【"+r.data.param.name+
"】，该项不能为空。");return}else if(q.length&&(m=y[o])&&!RegExp(m).test(q)){Mugeda.messageBox("【"+r.data.param.name+"】的内容（"+q+"）的格式不正确。请检查后重试。");return}k&&(k=k.replace(/#/g,"_"),i+="&"+k+"="+q,t++)}}if(t==0)return;j+="?"+i;if(Object.keys(h).length>0)for(d in h)d.indexOf("#")?(b=h[d],d=d.replace(/#/g,"_"),j+="&"+d+"="+b):j+="&"+d+"="+h[d];if(a.extraData)for(var z in a.extraData)j+=
"&"+z+"="+a.extraData[z];/_mrcmc=(.*?)(\&|$|\#)/.test(location.search)&&(j+="&_mrcmc="+RegExp.$1);/_mrcsc=(.*?)(\&|$|\#)/.test(location.search)&&(j+="&_mrcsc="+RegExp.$1);j+="&_msuid="+getMsuid();MugedaTools.message.show("正在提交");ajaxHelper({url:j,type:"jsonp",mode:"iframe",jsonp_callback:"form_callback",success:function(a){MugedaTools.message.close();e&&e(a)},error:function(a){MugedaTools.message.close();e&&e({status:a.status})}})}}d="actoin_type="+a.type+"&refid="+(new Date).getTime();
for(item in a.param)d+="&"+item+"="+a.param[item];f&&c&&a.param.event_name&&MugedaTracker.fireEvent({category:"interaction",action:a.param.event_name,label:d,value:0})},processCloseButton:function(a,b){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var c=b,e=null;if(!c)try{window!=window.parent?(c=window.parent.document,e=window.frameElement):c=document}catch(f){c=document}if(c){var d=null;try{d=window.parent.document,d.getElementById("mugeda_expanded")||d.createElement("div")}catch(g){return}var j=
a||_mrmcp.display_mode,i=MugedaMraid.mraidReadyStatus==1?mraid.getPlacementType():"default",h=c.getElementById("mugeda_close_button");if(!h)h=c.createElement("img"),h.id="mugeda_close_button",h.style.cursor="pointer",h.style.zIndex=99999,h.style.display="block",h.style.position="fixed",h.style.right="0",h.style.top="0",h.addEventListener("click",function(){if(MugedaMraid.mraidReadyStatus!=1){c.body.removeChild(h);j=="interstitial"&&e&&e.parentNode.removeChild(e);var a=c.getElementById("mugeda_expanded");
a&&c.body.removeChild(a)}}),c.body.appendChild(h);if(i=="interstitial"||j=="auto"||j=="resize"||j=="expand"||j=="interstitial")h.src=creative_path+"images/close_button.png",h.onerror=function(){h.style.display="none"},h.onload=function(){h.style.display=i=="interstitial"||j!="auto"?"block":"none"}}},setupMobileActionCallback:function(a){MugedaBehavior.actionCallback=a},setupMobileActions:function(a,b,c){function e(a){var c=navigator.userAgent.toLowerCase().indexOf("android")>-1,d=c?15:20,e=c?5:10,
t=function(a,g,k,m){if(Math.sqrt(a*a+g*g+k*k)>=(m?d:e)){a=(new Date).getTime();g=a-(MugedaBehavior.lastHitTime||0);if(!MugedaBehavior.lastHitTime||g>200)MugedaBehavior.shakeNum++,MugedaBehavior.lastHitTime=a;else if(g>1E3)MugedaBehavior.shakeNum=0;if(MugedaBehavior.shakeNum>=(c?1:2)){for(var p in MugedaBehavior.shakeHash){a=MugedaBehavior.shakeHash[p];for(g=0;g<a.length;g++)info=a[g],k=info.object,k=k.displayObject?k.displayObject.realVisible:true,info.callback&&k&&(MugedaBehavior.processAction(info.behavior,
info.behavior.event,true),info.callback())}MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,b.event);MugedaBehavior.shakeNum=0}}},p=0,k=0,m=0;if(a.acceleration===null||a.acceleration.x===void 0||a.acceleration.y===void 0||a.acceleration.z===void 0||a.acceleration.x===null||a.acceleration.y===null||a.acceleration.z===null){if(a.accelerationIncludingGravity)p=a.accelerationIncludingGravity.x,k=a.accelerationIncludingGravity.y,m=a.accelerationIncludingGravity.z,t(p,k,m,1)}else p=a.acceleration.x,
k=a.acceleration.y,m=a.acceleration.z,t(p,k,m,0)}var f=a.dataRef||a.aniData;isMobile();isMobile();isMobile();if(b.event=="shake"&&window.DeviceMotionEvent){if(!window.mugedaShakeHooked)MugedaBehavior.shakeNum=0,window.addEventListener("devicemotion",e,false),window.mugedaShakeHooked=true;var d=a.aniData?a.aniData.guid:null;d&&(MugedaBehavior.shakeHash[d]||(MugedaBehavior.shakeHash[d]=[]),MugedaBehavior.shakeHash[d].push({object:a,callback:c,behavior:b}))}}};
MugedaTracker={fireEvent:function(a){if(!window.location||!window.location.host){var a=(_mrmcp.track_bot||"//cdn.mugeda.com/media/pages/track/track_20131030.html")+"?"+(typeof _mrmma_var1==="undefined"?"var1=none":_mrmma_var1)+"&"+(typeof _mrmma_var2==="undefined"?"var2=none":_mrmma_var2)+"&category="+a.category+"&action="+a.action+"&label="+encodeURIComponent(a.label)+"&value="+a.value+"&noninteraction="+a.noninteraction,b=document.createElement("iframe");b.id=_mrmcp.creative_id;b.src=a;b.style.display=
"none";b.style.width="1px";b.style.height="1px";document.body.appendChild(b)}else if(this.fireGAEvent(a.category,a.action,a.label,a.value,a.noninteraction),this.fireMUEvent(a.category,a.action,a.label,a.value),window.mugedaGetCustomTracker&&(b=window.mugedaGetCustomTracker())){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var c=_mrmcp.custom_params,e=_mrmma_tags;c&&c.indexOf("%CUSTOMPARAM%")<0&&(e+="&"+c);b(e,a.category,a.action,a.label,a.value)}},fireGAEvent:function(a,b,c,e,f){typeof _gaq!="undefined"&&
(_gaq.push(["_trackEvent",a,b,c,e,f]),typeof _ga_mugeda_use_custom!="undefined"&&_gaq.push(["custom._trackEvent",a,b,c,e,f]))},fireMUEvent:function(a,b,c,e){typeof _mugeda_tracker!="undefined"&&_mugeda_tracker.trackEvent({action:b,category:a,label:c,value:e})}};
function mraidReady(){parseFloat(mraid.getVersion())-0.999>0?(MugedaMraid.mraidReadyStatus=1,_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp,_mrmcp.display_mode&&(mraid.useCustomClose(true),MugedaBehavior.processCloseButton()),mraid.addEventListener("error",function(){}),mraid.addEventListener("stateChange",function(){var a=mraid.getState();MugedaMraid.setMraidState(a)}),mraid.addEventListener("sizeChange",function(){})):console.log("mraidReady is called, but with no correct version (>= 1.0) supported.")}
var mraidReadyTimeout,mraidTimeOut=100,mraidCounter=0;function readyListener(){typeof mraid==="undefined"?(mraidCounter++,mraidCounter<mraidTimeOut&&(mraidReadyTimeout=setTimeout(readyListener,100))):mraid.getState()==="loading"?mraid.addEventListener("ready",mraidReady):mraidReady()}readyListener();
try{var htmlDoc=document.getElementsByTagName("head").item(0),js=document.createElement("script"),jsPath=(_mrmcp.script_sub_path||".")+"/",s=jsPath+"mraid.js";js.setAttribute("type","text/javascript");js.setAttribute("src",s);htmlDoc.appendChild(js);js.onload=function(){};js.onerror=function(){}}catch(e$$26){alert(e$$26.toString())}
function genSessionId(a){for(var b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),c=Number(+new Date).toString(36),e=0,f="",d=b.length;e<a;e++)f+=b[Math.floor(Math.random()*d)];return c+f.toLowerCase()}
Mugeda.playEmbeddedVideo=function(a){a=a.target.parentElement;a.style.display="none";for(var b=0;b<a.parentElement.children.length;b++)a.parentElement.children[b].setAttribute("contenteditable","false");var c=a.previousSibling;c.play();c.onclick=function(){c.controls=c.paused?false:true;c.paused?c.play():c.pause()};if(navigator.userAgent.match(/mqqbrowser.*tbs/i)){for(var e=null;;)if(a=a.parentElement,a.className.indexOf("mugeda_richText_content")>=0){e=a.parentElement;break}else if(a==document.body)break;
var a=e.scrollTop,f=document.createElement("div");f.className="qbrowser_workaround";f.style.position="absolute";f.style.width="1px";f.style.height="1px";f.style.left=0;f.style.top=a+"px";e.appendChild(f);if(e)e.onscroll=function(){f.style.top=e.scrollTop+"px"}}};
Mugeda.DataStats={onEventCallback:null,newsetData:{},init:function(a){this.isPreview=location.pathname==="/client/preview_css3.html"&&/mugeda.com$/.test(location.host);if(!this.isPreview){this.viewId=function(){var a=Math.random().toString().substr(2,4)+""+(new Date-new Date("2012/1/1"));return Number(a).toString(36)}();this.crid=_mrmcp.creative_id||Mugeda.data.crid||null;this.currentPageId=a.indexPageId;this.lockTime=false;this["static"]=false;this.staticSecond=0;this.msuid=getMsuid();var b=localStorage||
window.localStorage||null;if(b){for(var c=[],e=0;e<b.length;e++){var f=b.key(e);f.indexOf("leaveData_")>-1&&c.push(f)}if(c.length)for(e=0;e<c.length;e++){var d=c[e];if(f=localStorage.getItem(d))f=JSON.parse(f),f.isLeave=true,this.uploadData(f,null,null,function(){b.removeItem(d)})}}if(this.crid&&!this.isStart){this.isStart=true;if(!this.videoHash)this.videoHash={};this.statData={crid:this.crid,viewId:this.viewId,pages:[]};this.entry({type:"loadTime",indexPageId:a.indexPageId});this.bindTimer()}}},
bindTimer:function(){var a=this,b=(new Date).getTime(),c=0;a.second=1;var e=function(){c++;var f=1E3-((new Date).getTime()-(b+c*1E3));f<0&&(f=0);setTimeout(e,f);if(!a.lockTime)f=a.getCurrentPage(),a["static"]=a.staticSecond>60?true:false,a.second===10&&!a["static"]?(a.legalTime(f.stayTime)&&(f.stayTime+=1E3),f={crid:a.crid,viewId:a.viewId,pages:[{id:a.currentPageId,stayTime:f.stayTime}]},a.second=1,a.uploadData(f)):(a.legalTime(f.stayTime)&&(f.stayTime+=1E3),a.updateNewsetData({pages:[f],crid:a.crid,
viewId:a.viewId}),a.second++),a.staticSecond++};setTimeout(e,1E3)},getCurrentPage:function(){for(var a,b=this.statData.pages,c=0;c<b.length;c++)b[c].id==this.currentPageId&&(a=b[c]);return a},entry:function(a){a=a||{};if(!this.isPreview){if(a){var b=a.type;this.staticSecond=0;switch(b){case "loadTime":this.loadTime(a);break;case "updatePageTime":this.updatePageTime(a);break;case "interActions":this.interActions(a);break;case "playVideo":this.playVideo(a);break;case "stopVideo":this.stopVideo(a)}}if(a.event&&
this.onEventCallback)this.onEventCallback({event:a.event})}},legalTime:function(a){return a<0||a>864E5?false:true},loadTime:function(a){var b=(new Date).valueOf()-performance.timing.connectStart,a=a.indexPageId;this.legalTime(b)&&this.uploadData({crid:this.crid,viewId:this.viewId,loadTime:b,pages:[{id:a,stayTime:0}]});this.statData.pages.push({id:a,stayTime:0})},updatePageTime:function(a){if(this.statData){var b=this.statData.pages;if(b.length){for(var c=false,e=0;e<b.length;e++)b[e].id==a.toId&&
(c=true);c||b.push({id:a.toId,stayTime:0})}else console.log("逻辑错误");c={crid:this.crid,viewId:this.viewId,pages:[],media:[]};for(e=0;e<b.length;e++)(b[e].id==a.fromId||b[e].id==a.toId)&&c.pages.push(b[e]);this.currentPageId=a.toId;this.uploadData(c)}},interActions:function(a){if(this.statData){var b={crid:this.crid,viewId:this.viewId,pages:[],interactions:[],media:[]},c=this.getCurrentPage();c?(b.pages.push(c),b.interactions=a.data,this.uploadData(b)):console.log("逻辑错误,没有拿到当前页数据.")}},
playVideo:function(a){var b=a.id,c=this.videoHash;if(!c)c=this.videoHash={};c[b]?c[b].isUpdate=true:c[b]={id:b,viewLength:0,belong:this.currentPageId,isUpdate:true,video:a.target}},stopVideo:function(a){var a=a.id,b=this.videoHash;if(b[a]){var c=b[a].target||document.querySelector('[data-guid="'+a+'"] video');b[a].viewLength=Math.floor((c?c.currentTime:0)*1E3)}else console.log("逻辑错误,没有找到视频.")},updateNewsetData:function(a){var b=this.newsetData,c=function(a,
c,b){var g={};a[b].map(function(a){g[a.id]=a});for(var j=0;j<c[b].length;j++){var i=c[b][j],h=g[i.id];if(h){if(b=="media"&&h.viewLength!==void 0&&i.viewLength!==void 0)h.viewLength=Math.max(i.viewLength,h.viewLength);if(h.stayTime!==void 0&&i.stayTime!==void 0)h.stayTime=Math.max(i.stayTime,h.stayTime);if(i.action=="submitForm")h.formCount=(h.formCount||0)+1}else if(a[b].push(i),g[i.id]=i,i.action=="submitForm")delete g[i.id].data,g[i.id].formCount=(g[i.id].formCount||0)+1}};b.reportTime=(new Date).getTime();
b.mode="full";if(a.connectionType&&!b.connectionType)b.connectionType=a.connectionType;if(a.crid&&!b.crid)b.crid=a.crid;if(a.msuid&&!b.msuid)b.msuid=a.msuid;if(a.viewId&&!b.viewId)b.viewId=a.viewId;if(a.loadTime&&!b.loadTime)b.loadTime=a.loadTime;if(a.profile)b.profile=a.profile;if(a.media&&a.media.length)b.media&&b.media.length?c(b,a,"media"):b.media=a.media;if(a.pages&&a.pages.length)b.pages&&b.pages.length?c(b,a,"pages"):b.pages=a.pages;if(a.interactions&&a.interactions.length)b.interactions&&
a.interactions.length?c(b,a,"interactions"):b.interactions=a.interactions;localStorage.setItem("leaveData_"+this.crid,JSON.stringify(b));return b},getQueryString:function(a){a=window.location.search.substr(1).match(RegExp("(^|&)"+a+"=([^&]*)(&|$)"));return a!=null?decodeURIComponent(a[2]):null},getNetworkType:function(){try{var a=navigator.userAgent,b=a.match(/NetType\/\w+/)?a.match(/NetType\/\w+/)[0]:"NetType/other",b=b.toLowerCase().replace("nettype/",""),c;if(navigator.connection&&navigator.connection.type)return navigator.connection.type;
switch(b){case "wifi":c="wifi";break;case "4g":c="4g";break;case "3g":c="3g";break;case "3gnet":c="3g";break;case "2g":c="2g";break;default:c="other"}return c}catch(e){return"other"}},uploadData:function(a,b,c,e){var f=this,d=JSON.parse(JSON.stringify(a));e&&e();f.lockTime=true;e="//"+f.crid+".stat.mugeda.com/stats/c.gif";d.media&&d.media.length===0&&delete a.media;d.msuid=f.msuid;a={};if(f.getQueryString("avatar"))a.avatar=f.getQueryString("avatar");if(f.getQueryString("nickname"))a.nickname=f.getQueryString("nickname");
if(f.getQueryString("openid"))a.openid=f.getQueryString("openid");d.profile=a;d.connectionType=f.getNetworkType();if(d.crid.length!=24)if(a=d.crid.split("/"),a.length)a.forEach(function(a){if(a.length==24)d.crid=a});else return;if(a=f.videoHash)for(key in a){var g=a[key].target||document.querySelector('[data-guid="'+key+'"] video'),g=Math.floor(g?g.currentTime*1E3:a[key].viewLength||0);if(a[key].belong==f.currentPageId){if(!d.media)d.media=[];d.media.push({id:key,viewLength:g})}}d.isLeave||(d=f.updateNewsetData(d));
a=JSON.stringify(d);a=Base64.encode(encodeURIComponent(a));console.log(JSON.parse(decodeURIComponent(Base64.decode(a))));var g=new Image,j="";d.viewId&&(j+="&vi="+d.viewId);d.reportTime&&(j+="&tm="+d.reportTime);d.mode&&(j+="&md="+d.mode);d.crid&&(j+="&crid="+d.crid);g.src=e+"?random="+Math.random()+"&data="+a+j;g.onload=function(){b&&b();f.lockTime=false};g.onerror=function(){c&&c();f.lockTime=false};f.second=1}};
Mugeda.Analytics=function(a,b){var c=[],e=0,f=_mrmcp.impression_pixel?_mrmcp.impression_pixel.indexOf("%TRACKURL%")>=0?"":_mrmcp.impression_pixel:"",a=a||f||"//"+_mrmcp.creative_id+".stat.mugeda.com/stats/c.gif",b=b||_mrmcp.eventUrl||a;this.setAccount=function(){};this.setCustomVar=function(a,b,d){a=a||0;c[a]&&delete c[a];c[a]={};c[a][b]=d||""};var d=function(){getCookie("clientId");for(var a=[],b=0;b<c.length;b++)for(var d in c[b])a[b]=d+"="+encodeURIComponent(c[b][d]);return a.join("&")},g=function(){var a=
location.pathname,b=/(?:\/animation\/edit)|(?:\/page\/edit)|(?:\/default\/preview\.html)|(?:\/client\/preview(?:_css3)?\.html)/;return!location.host||b.test(a)?false:true};this.trackPageview=function(b){if(g()){this.startTime=(new Date).getTime();var c=a,f=new Image,t=c.indexOf("?")!=-1?"&":"?",p=_mrmcp.title||window._mrmma_title,k=+new Date,m=window.location.host,r=(_mrmcp.width||window._mrmma_width||0)+"x"+(_mrmcp.height||window._mrmma_height||0),q=window.location.href.slice(window.location.href.indexOf("/",
8)),o=screen.width+"x"+screen.height,b=b||{};b.msv="0.1.0";b.msa="MU-A001";b.msh=m;b.mscs=r;b.msp=q;b.mssr=o;b.mssi=genSessionId(16);b.mscn=p;b.msct=k;b.crid=_mrmcp.creative_id||"";for(var y in b)b.hasOwnProperty(y)&&(this.setCustomVar(e,y,b[y]),e++);var z=this;getMsuid(function(){z.setCustomVar(e++,"msuid",getMsuid());var a=d();f.src=c+t+("md=pv&mst=1&"+a)})}};this.trackEvent=function(a){if(g()){var c=new Image,e=b,f=e.indexOf("?")!=-1?"&":"?",p=d(),a=a||{},k=(new Date).getTime(),m=k-this.startTime,
r=encodeURIComponent(a.action||"submit"),q=encodeURIComponent(a.categroy||"weika"),o=encodeURIComponent(a.label||""),a=parseInt(a.value)||0;c.src=e+f+p+"&mst=2&msts="+k+"&msetd="+m+"&msen="+r+"&msev="+a+"&msec="+q+"&msel="+o}}};try{if(window._mrmcp&&window._mrmcp.publish_time)window._mugeda_tracker=new Mugeda.Analytics,_mugeda_tracker.trackPageview()}catch(e$$27){}
function createFontFaceStyle(a,b,c,e,f,d,g){if(!b)return f&&f(a,null),a;var g=g||{},j="cloudfont-"+b;c&&(j+="-"+c);var i=document.getElementById(j),d=Object.prototype.toString.call(e)==="[object Array]"&&typeof f==="function",h=function(a){return(a=RegExp("[?&]"+a+"=([^&#]*)").exec(window.location.href))?a[1]:0};a.toLowerCase()=="simhei"?a='"Microsoft YaHei", "微软雅黑", SimHei, sans-serif':c&&(a+="-"+c);if(i)if(d&&g.useBlob&&i.data)return f(a,i.data),a;else if(!g.useBlob)return d&&
(b=i.textContent.match(/src:url\((.*?)\)/),f(a,b?b[1]:null)),a;var g=(g=h("fontApiType"))?g:3,i=e||["eot","eot","woff","ttf","svg"],t=b.indexOf("?")>-1?"&":"?";window.bd_version||h("v");for(var h=[],p=e&&e.length,k=e=0,m=function(a,b){var d=document.querySelector(".cloudfont_"+c);d&&document.head.removeChild(d);var e=document.createElement("style"),f,g=function(a){e.id=j;e.className="cloudfont_"+c;a=document.createTextNode(a);e.type="text/css";e.data=b;e.appendChild(a);document.head.appendChild(e)};
if(b&&b.type!="text/html"){var h,i=new window.FileReader;i.readAsDataURL(b);i.onloadend=function(){h=i.result;f="@font-face {font-family:'"+a+"';\nsrc:url("+h+");}";g(f)}}else a.indexOf("cloud-")!=0&&(f="@font-face {font-family:'"+a+"';}",g(f))},r=function(b){ajaxHelper({url:b,cache_ok:true,type:"data",success:function(b){++k===p&&typeof f==="function"&&(m(a,b),f(a,b))},error:function(a){a.status==414&&Mugeda.messageBox(Lang.M_TextTooLong);if(--p===0)throw f(false),"request font failed";}})},q=0,
o=i.length;q<o;q++){var y=b+t+"format="+i[q]+"&api_type="+g,z="url("+y+")";if(q>0){var A=i[q];i[q]==="eot"?A="embedded-opentype":i[q]==="ttf"&&(A="truetype");z+=" format('"+A+"')"}h.push(z);d&&(e++,r(y))}if(d&&e===0)throw"request type invalid";return d?null:a}
Mugeda.messageBox=function(a,b,c,e){var e=e||{},f=document.createElement("div");f.id="message_holder_"+(new Date).getTime();f.style.display="block";f.style.position="absolute";f.style.left=0;f.style.top=0;f.style.width="100%";f.style.height="100%";f.style.zIndex=2E5;var d=document.createElement("div");d.className="messageMask";d.style.display="block";d.style.position="absolute";d.style.left=0;d.style.top=0;d.style.width="100%";d.style.height="100%";d.style.backgroundColor="rgba(0,0,0,0.5)";f.appendChild(d);
var b=b||"alert",g=document.createElement("div");g.className="messageInfo";g.style.display="block";g.style.position="absolute";if(e.width)g.style.width=e.width+"px";g.innerHTML='<div class="messageBody">'+a+'</div><div align="center" class="messageConfirm '+b+'" onclick="onConfirmMessage();">'+(e.okText||"确认")+'</div><div align="center" class="messageCancel '+b+'" onclick="onCancelMessage();">'+(e.cancelText||"取消")+"</div>";f.appendChild(g);document.body.appendChild(f);f.querySelector(".messageConfirm").onclick=
function(){document.body.removeChild(f);c&&c(true)};f.querySelector(".messageCancel").onclick=function(){document.body.removeChild(f);c&&c(false)};f.querySelector(".messageMask").onclick=function(){g.className="messageInfo blinking";setTimeout(function(){g.className="messageInfo"},800)};a=document.getElementById("mugeda_message_styles");if(!a)a=document.createElement("style"),a.type="text/css",a.id="mugeda_message_styles",a.innerHTML=".messageBody { padding:32px; background-color: #fff; border-top-left-radius: 4px; border-top-right-radius: 4px; }.messageInfo { max-width: 512px; min-width: 256px; margin-left:50%; transform: translate(-50%, -50%); margin-top: 256px; font-size:14px; border: 4px solid rgba(0,0,0,0); border-radius:8px; line-height: 20px; }.messageConfirm, .messageCancel { width: 50%; display: inline-block; height: 48px; line-height: 48px; color: #fff; cursor: pointer; }.messageConfirm.alert { width: 100%; }.messageCancel.alert { display: none;}.messageCancel:active, .messageConfirm:active {-webkit-filter: brightness(115%);}.messageConfirm { background-color: #F36523; border-bottom-left-radius: 4px;}.messageInfo.blinking{ -webkit-animation: blinking 200ms infinite step-end; animation: blinking 200ms infinite step-end; }@-webkit-keyframes blinking {0% {border-color: rgba(255,0,0,0);} 50% {border-color: rgba(255,0,0,0.6);}}@keyframes blinking {0% { border-color: rgba(255,0,0,0);} 50% { border-color: rgba(255,0,0,0.6);}}.messageCancel { background-color: #999; border-bottom-right-radius: 4px;}",
document.body.appendChild(a)};
Mugeda.InstantMessage=function(){var a;return{show:function(b){var c=document.createElement("div"),e=c.appendChild(document.createElement("div")),f=e.appendChild(document.createElement("div")),d=e.appendChild(document.createElement("div"));c.style.cssText="position:fixed;left:0;right:0;top:0;bottom:0;text-align:center;line-height:"+(document.body.clientHeight||document.documentElement.clientHeight)+"px";e.style.cssText='padding-top:10px; line-height:30px;display:inline-block;padding:8px; min-width: 80px; background-color:rgba(0,0,0,0.6);border-radius:4px;"';e.align=
"center";f.style.cssText="width: 24px; height: 24px; display: block; border-radius: 50%; border-left: 2px solid #F36523; border-top: 2px solid #F36523; border-right: 2px solid white; border-bottom: 2px solid white; margin: 16px;";d.style.cssText='text-align:center;color:#fff;font:normal 12px "microsoft yahei";';d.innerHTML=b;a=document.body.appendChild(c);b=StyleSheetManager.insertKeyframes("from {"+Browser.prefix.css+"transform:rotate( 0deg ) }to {"+Browser.prefix.css+"transform:rotate( 360deg ) }");
f.style.cssText+=Browser.prefix.css+"animation:"+b+" 1200ms linear infinite;"},close:function(){a&&(a.parentNode.removeChild(a),a=null)}}}();
