;(function(){'use strict';var bn=MugineRequire("Utils/Module"),cn=MugineRequire("Text/TextField"),dn=MugineRequire("Utils/Plugin"),en=MugineRequire("Geom/Color");function fn(){fn.j.constructor.apply(this,arguments);this.Wi="";this.Ch=this.Xi=null}bn.extend(fn,cn);fn.prototype.K="Text";
fn.Jb=function(a,b){function c(){c.j.constructor.apply(this,arguments);this.Wi=f;this.Ch=g;if(e.hintColor)this.Xi=en.parse(e.hintColor);else{var a=this.Id.fd.clone();a.Tl(.5);this.Xi=a}this.$a("")}var d=cn.Jb(a,b);bn.extend(d,fn);var e=a.param,f=e.textContent,g=e.inputType;bn.extend(c,d);return c};bn.H("Text.InputBox",fn);dn.be(2031,fn);var gn=MugineRequire("Utils/Module"),hn=MugineRequire("Utils/Browser"),jn=MugineRequire("Render/RenderObjectTextField"),ln=MugineRequire("Render/StyleSheet"),mn=MugineRequire("Utils/Plugin"),nn=MugineRequire("Render/RenderObject");function on(){on.j.constructor.apply(this,arguments)}gn.extend(on,jn);nn.Ra=function(a){return nn.hg[a]};var pn=on.prototype;
pn.Oa=function(){var a=this.c,b=this.gt(),c=a.Id,d=a.u.wa,e="";d.nb&&0<d.nb.ga&&(e+=hn.prefix.f+"text-stroke:"+d.Nb/1+"px "+d.nb.Eb()+";");c=ln.V("position: absolute; outline: none; padding: 0; background: transparent; border-radius: 0; border: 0; width: "+a.ta+"px; height: "+a.sa+"px;"+hn.prefix.f+"transform-origin: left top;"+hn.prefix.f+"appearance:none;"+hn.prefix.f+"user-select: initial;"+e+"font-family: "+c.Mj+";text-align: "+c.Yg+";color: "+c.fd.Eb()+";font-size: "+d.Db+"px;"+(c.Cj?"font-weight: bold;":
"")+(c.em?"text-decoration: underline;":"")+(c.Zj?"font-style: italic;":"")+(a.Kd?"cursor: pointer;":""));this.va.push(c);this.md=c;e="color: "+a.Xi.Eb();if(hn.Zh.dF)var f=c+"::-webkit-input-placeholder";else hn.Zh.AD?f=19>parseInt(hn.Zh.version)?c+":-moz-placeholder":c+"::-moz-placeholder":hn.Zh.lw&&(f=c+":-ms-input-placeholder");ln.V(f,e);"textArea"==a.Ch?(e="","0"==b.lineHeight?e="normal":b.lineHeight&&(e="line-height:"+b.lineHeight+"px;"),this.fa='<textArea ondragstart="return false;" data-type="input-box" data-mid="'+
a.o+'"'+(a.W?' data-guid="'+a.W+'"':"")+' class="{{className}}" placeholder="'+unescape(a.Wi)+'"style="'+e+'"></textArea>'):(e=(b=0<=["date","time"].indexOf(a.Ch))?"value":"placeholder",f=unescape(a.Wi),b&&f&&a.$a(f),this.fa='<input ondragstart="return false;" data-type="input-box" data-mid="'+a.o+'"'+(a.W?' data-guid="'+a.W+'"':"")+' class="{{className}}" type="'+a.Ch+'" '+e+'="'+f+'"/>')};pn.Au=function(){return this.Z().tagName};var qn=null;
pn.Qy=function(){var a=document.getElementById("_AnalogInput"),b=document.getElementById("_AnalogArea"),c=nn.Ra(0).Z();a||(a=document.createElement("span"),a.style.zIndex="10",a.style.position="absolute",a.style.left="-9999px",a.id="_AnalogInput",c.appendChild(a));b||(b=document.createElement("textarea"),b.style.zIndex="10",b.style.position="absolute",b.style.left="-9999px",b.id="_AnalogArea",b.style.height="0",c.appendChild(b))};
pn.Qb=function(){on.j.Qb.apply(this,arguments);this.Z().addEventListener("change",this.Gy.bind(this));this.Z().addEventListener("input",this.cB.bind(this));this.Z().addEventListener("focus",this.dz.bind(this));this.Z().addEventListener("click",this.Ly.bind(this));this.Qy()};pn.gt=function(){var a=this.c.A.param;return{importLimit:a.importLimit,limitCharset:a.limitCharset,lengthItem:a.lengthItem,lengthLimit:a.lengthLimit,lineHeight:a.inputLineheight}};
pn.eB=function(a){var b=this.Z(),c=this.gt(),d=b.value;if(!c.importLimit&&!c.lengthItem||"0"==c.importLimit&&"0"==c.lengthItem)a&&a(d);else{var e=!1,f=document.getElementById("_AnalogInput"),g=document.getElementById("_AnalogArea"),h=this.Au();if(c.importLimit)switch(c.importLimit){case "1":var k=d.match(/[一-龥]/gi)||[],k=k.join("");k!=d&&(d=k,Mugeda.messageBox("请只输入中文。",null,function(){a&&a(d)}),e=!0);break;case "2":k=d.match(/[a-z]/gi)||[];k=k.join("");
k!=d&&(d=k,Mugeda.messageBox("请只输入英文。",null,function(){a&&a(d)}),e=!0);break;case "4":if(c.limitCharset){k=c.limitCharset;c.limitCharset+="\n";for(var l=!1,n=0;n<d.length;)-1==c.limitCharset.indexOf(d[n])?(d=d.replace(d[n],""),l=!0):n++;l&&(Mugeda.messageBox("请只输入如下字符：（"+k+"）",null,function(){a&&a(d)}),e=!0)}}if(!e)if("INPUT"==h){if(d=d.replace(/\s/gi,"&nbsp;"),f.innerHTML=d,d=d.replace(/\&nbsp;/g," "),g=b.offsetWidth,
b=f.offsetWidth,c.lengthItem&&0!=c.lengthItem)switch(c.lengthItem){case "1":b=parseInt(c.lengthLimit);c.lengthLimit&&d.length>b&&(d=d.substr(0,b),f.innerHTML=d,Mugeda.messageBox("最多可以输入 "+b+" 个字符。",null,function(){a&&a(d)}),e=!0);break;case "2":if(b>g)for(c=0;c<d.length;c++)b>g&&(d=d.substring(0,d.length-1),f.innerHTML=d,b=f.offsetWidth,Mugeda.messageBox("输入超出了允许的长度范围。",null,function(){a&&
a(d)}),e=!0)}}else if("TEXTAREA"==h&&c.lengthItem&&0!=c.lengthItem)switch(c.lengthItem){case "1":b=parseInt(c.lengthLimit);c.lengthLimit&&d.length>b&&(d=d.substr(0,b));g.value=d;break;case "2":g.value=d,f=parseInt(window.getComputedStyle(b).lineHeight)||39,Math.round(g.scrollHeight/f)>=Math.round(b.scrollHeight/f)?g.value=qn:qn=d}!e&&a&&a(d)}};pn.cB=function(){};pn.Ly=function(){var a=this.Z();document.activeElement!=a&&a.focus()};
pn.dz=function(){var a=this.Z(),b=this.Au(),c=document.getElementById("_AnalogInput"),d=document.getElementById("_AnalogArea"),e=window.getComputedStyle(a);"INPUT"==b?(c.style.font=e.font,c.style.transform=e.transform,c.style.left="-9999px"):"TEXTAREA"==b&&(d.style.font=e.font,d.style.transform=e.transform,d.style.overflowY="hidden",d.style.width=a.offsetWidth+"px",d.style.padding=0,d.style.border="none",d.style.left="-9999px")};
pn.Gy=function(){var a=this,b=a.Z(),c=b.value;a.eB(function(d){c!=d&&(b.value=d,b.focus(),b.select());a.c.$a(d)})};pn.s=function(){var a=this.Z();if(document.activeElement==a){var b=a.getBoundingClientRect(),a=b.top,c=b.bottom,b=gn.Ck(),a=(a+c)/2,b=b.height,c=this.c.Va().R.Of;if(0>a||a>b)c.style.cssText+=hn.prefix.f+"transform: translateY(-200px);"}};
pn.ua=function(a,b,c){var d=this.c;on.j.constructor.j.ua.apply(this,arguments);document.activeElement!==this.Z()&&(d=d.ub(),d!=this.ha.value&&(this.ha.value=d))};mn.ce(2031,on);
})();